[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "django-api-gateway"
version = "0.1.0"
description = "API Gateway with Django and IFTTT-like interface"
readme = "README.md"
authors = [
    {name = "OpenHands", email = "openhands@all-hands.dev"}
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Framework :: Django",
]
requires-python = ">=3.8"
dependencies = [
    "django>=5.0.0",
    "djangorestframework>=3.14.0",
    "requests>=2.28.0",
    "coreapi>=2.3.3",
    "pyyaml>=6.0",
]

[tool.setuptools]
packages = ["api_gateway_project", "gateway"]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-django>=4.5.2",
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
]

[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310", "py311", "py312"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 88

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "api_gateway_project.settings"
python_files = ["test_*.py", "*_test.py"]