# Generated by Django 5.2.1 on 2025-05-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cat_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catimage",
            name="breed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_images",
                to="cat_api.catbreed",
            ),
        ),
    ]
