# Generated by Django 5.2.1 on 2025-05-10 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sheet_id",
                    models.CharField(max_length=255, verbose_name="Google Sheet ID"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Sheet Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_sheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Sheet",
                "verbose_name_plural": "Google Sheets",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SheetData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_data", models.JSONField(verbose_name="Row Data")),
                ("row_number", models.PositiveIntegerField(verbose_name="Row Number")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="google_sheets.googlesheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sheet Data",
                "verbose_name_plural": "Sheet Data",
                "ordering": ["row_number"],
                "unique_together": {("sheet", "row_number")},
            },
        ),
    ]
